---
# tasks file for checkusers

- name: Check for accounts with username/password
  shell: cat /etc/shadow | grep -vE ':([!*]|!)'
  register: password_accounts
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Check for unauthorized SSH keys
  shell: |
    for X in $(cut -f6 -d ':' /etc/passwd |sort |uniq); do
      if [ -s "${X}/.ssh/authorized_keys" ]; then
        cat "${X}/.ssh/authorized_keys"
      fi;
    done
  register: authorized_keys
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Print password accounts
  debug:
    var: password_accounts.stdout_lines

- name: Print unauthorized SSH keys
  debug:
    var: authorized_keys.stdout_lines