---
# tasks file for checkusers
- name: Get all user info 
  shell: cat /etc/shadow | grep -vE ':([!*]|!)'
  register: userspass

  #getent:
  #  database: passwd
  #  key: root

- name: Show all user info
  debug:
    var: userspass.stdout_lines